framework:
    mailer:
        dsn: '%env(MAILER_DSN)%'

   # swiftmailer:
   # transport: smtp
   # host: 'smtp.gmail.com'
    # port: 465
    #encryption: ssl
    #username: 'testeurmailler@gmail.comm'
    #password: 'Admin123$'

